# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f27c1b37bf6c70bd0f6131be2b405dcd5ac0e1152c8850dc666097477f4f240e5a42e4504b3348d7e1928f926f4112a4175ee7c0414650ced8c87a7eb480a684

test:
  secret_key_base: e3745b3ae6d25d076c235c1b81cbf04b13a5c4935cacb3f852ff2c481cd109d8adb9d0b2eba931d5e6fe6dce1948b5ad1dcce326eea6ed9055ca3b8e111ac83e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
